import streamlit as st

# Comprehensive movie data with 50 movies across multiple genres
movies = {
    "Action": [
        "Mad Max: Fury Road",
        "John Wick",
        "Die Hard",
        "The Dark Knight",
        "Gladiator",
        "The Avengers",
        "Black Panther",
        "Inception",
        "Casino Royale",
        "The Bourne Identity",
        "Thor: Ragnarok",
        "Terminator 2: Judgment Day",
        "Speed",
        "The Matrix",
        "Django Unchained",
        "Kill Bill: Vol. 1",
        "Mission: Impossible - Fallout",
        "Skyfall",
        "300",
        "Lethal Weapon",
        "Transformers",
        "Pacific Rim",
        "Sherlock Holmes",
        "The Equalizer",
        "Kingsman: The Secret Service",
        "RoboCop",
        "The Transporter",
        "Atomic Blonde",
        "Deadpool",
        "Jumanji: Welcome to the Jungle",
        "Die Hard with a Vengeance",
        "The Bourne Supremacy",
        "Edge of Tomorrow",
        "Oldboy",
        "National Treasure",
        "13 Hours: The Secret Soldiers of Benghazi",
        "Unstoppable",
        "Jack Reacher",
        "Rambo: First Blood Part II",
        "Ninja Assassin",
        "Bourne Ultimatum",
        "Warrior",
        "Train to Busan",
        "Furious 7",
        "Extraction",
        "The Man from U.N.C.L.E."
    ],
    "Comedy": [
        "Superbad",
        "The Hangover",
        "Step Brothers",
        "Bridesmaids",
        "Groundhog Day",
        "Zoolander",
        "Anchorman",
        "Mean Girls",
        "The 40-Year-Old Virgin",
        "Dumb and Dumber",
        "Pitch Perfect",
        "The Other Guys",
        "Hot Fuzz",
        "21 Jump Street",
        "Crazy Rich Asians",
        "The Grand Budapest Hotel",
        "Tropic Thunder",
        "Jojo Rabbit",
        "What We Do in the Shadows",
        "Forgetting Sarah Marshall",
        "The Princess Bride",
        "Anchorman 2: The Legend Continues",
        "Meet the Parents",
        "Dodgeball: A True Underdog Story",
        "The Nice Guys",
        "Groundhog Day",
        "Crazy, Stupid, Love",
        "She's All That",
        "The Heat",
        "How to Lose a Guy in 10 Days",
        "The Wedding Crashers",
        "Legally Blonde",
        "The Intern",
        "Napoleon Dynamite",
        "The Other Woman",
        "Freaky Friday",
        "Home Alone",
        "Mean Girls 2",
        "Bridesmaids 2",
        "I Love You, Beth Cooper",
        "Sex Drive",
        "Adventureland",
        "Step Up"
    ],
    "Drama": [
        "The Shawshank Redemption",
        "Forrest Gump",
        "The Godfather",
        "Pulp Fiction",
        "Fight Club",
        "12 Years a Slave",
        "The Social Network",
        "The Pursuit of Happyness",
        "A Beautiful Mind",
        "Moonlight",
        "The Revenant",
        "The Green Mile",
        "Dead Poets Society",
        "Schindler's List",
        "The King's Speech",
        "Little Women",
        "A Star is Born",
        "Spotlight",
        "The Florida Project",
        "Lady Bird",
        "The Help",
        "Manchester by the Sea",
        "The Imitation Game",
        "Room",
        "Whiplash",
        "Call Me by Your Name",
        "Silver Linings Playbook",
        "The Fighter",
        "Blue Valentine",
        "Doubt",
        "The Pursuit of Happyness",
        "Atonement",
        "Boyhood",
        "The Curious Case of Benjamin Button",
        "Her",
        "Inside Out",
        "Nomadland",
        "Joker",
        "The Trial of the Chicago 7",
        "Boys Don't Cry",
        "A Beautiful Day in the Neighborhood",
        "The Great Gatsby",
        "The Secret Life of Walter Mitty",
        "The Spectacular Now"
    ],
    "Horror": [
        "Get Out",
        "The Exorcist",
        "A Nightmare on Elm Street",
        "It",
        "The Shining",
        "Hereditary",
        "The Babadook",
        "The Conjuring",
        "It Follows",
        "Sinister",
        "A Quiet Place",
        "The Witch",
        "Midsommar",
        "Paranormal Activity",
        "The Cabin in the Woods",
        "Scream",
        "The Ring",
        "Saw",
        "The Invisible Man",
        "Us",
        "Pet Sematary",
        "Insidious",
        "The Nun",
        "Carrie",
        "The Grudge",
        "The Descent",
        "Train to Busan",
        "Evil Dead",
        "Happy Death Day",
        "The Purge",
        "Hereditary",
        "The Autopsy of Jane Doe",
        "The Lighthouse",
        "Don't Breathe",
        "Scream 2",
        "Jaws",
        "The Others",
        "Orphan",
        "The Conjuring 2",
        "Final Destination",
        "Sinister 2",
        "Annabelle",
        "The Texas Chain Saw Massacre"
    ],
    "Sci-Fi": [
        "Inception",
        "The Matrix",
        "Interstellar",
        "Blade Runner",
        "Star Wars",
        "E.T. the Extra-Terrestrial",
        "Arrival",
        "Ex Machina",
        "Jurassic Park",
        "Minority Report",
        "District 9",
        "The Fifth Element",
        "Children of Men",
        "Looper",
        "The Prestige",
        "Gravity",
        "The Martian",
        "Avatar",
        "Her",
        "War of the Worlds",
        "Total Recall",
        "Starship Troopers",
        "Gattaca",
        "The Time Machine",
        "Predestination",
        "Edge of Tomorrow",
        "Annihilation",
        "12 Monkeys",
        "The Terminator",
        "Tron",
        "Pacific Rim",
        "Ready Player One",
        "The Adjustment Bureau",
        "Battle Los Angeles",
        "I, Robot",
        "Dune",
        "Oblivion",
        "Source Code",
        "RoboCop",
        "The Island",
        "Gamer",
        "Chappie",
        "Snowpiercer",
        "A.I. Artificial Intelligence",
        "Total Recall"
    ],
    "Romance": [
        "The Notebook",
        "Pride and Prejudice",
        "La La Land",
        "Titanic",
        "Crazy, Stupid, Love",
        "Notting Hill",
        "When Harry Met Sally",
        "500 Days of Summer",
        "The Fault in Our Stars",
        "A Walk to Remember",
        "Love Actually",
        "10 Things I Hate About You",
        "The Vow",
        "Before Sunrise",
        "To All the Boys I've Loved Before",
        "Silver Linings Playbook",
        "The Age of Adaline",
        "Eat Pray Love",
        "Sweet Home Alabama",
        "The Best Exotic Marigold Hotel",
        "The Proposal",
        "Crazy Rich Asians",
        "Me Before You",
        "A Cinderella Story",
        "The Last Song",
        "Dear John",
        "Notting Hill",
        "How to Lose a Guy in 10 Days",
        "50 First Dates",
        "The Lucky One",
        "Serendipity",
        "The Time Traveler's Wife",
        "About Time",
        "P.S. I Love You",
        "Letters to Juliet",
        "The Longest Ride",
        "The Kissing Booth",
        "One Day",
        "The Wedding Planner",
        "Definitely, Maybe",
        "The Choice",
        "While You Were Sleeping",
        "The Wedding Date",
        "Hope Floats",
        "Someone Great"
    ],
    "Animation": [
        "Toy Story",
        "Finding Nemo",
        "Shrek",
        "The Lion King",
        "Up",
        "Spirited Away",
        "Inside Out",
        "Coco",
        "Frozen",
        "Zootopia",
        "Kung Fu Panda",
        "How to Train Your Dragon",
        "Wall-E",
        "Big Hero 6",
        "Moana",
        "Ratatouille",
        "The Incredibles",
        "Monsters, Inc.",
        "The Lego Movie",
        "Despicable Me",
        "Hotel Transylvania",
        "Coraline",
        "The Secret Life of Pets",
        "Sing",
        "The Iron Giant",
        "The Croods",
        "Shaun the Sheep Movie",
        "Over the Hedge",
        "ParaNorman",
        "Puss in Boots",
        "Tangled",
        "Kung Fu Panda 2",
        "Finding Dory",
        "Brave",
        "The Book of Life",
        "Wreck-It Ralph",
        "Cloudy with a Chance of Meatballs"
    ],
}

# Title of the app
st.title("Comprehensive Movie Recommendation App")

# Search bar for movie recommendations
search_query = st.text_input("Search for a movie or genre:")

# Filtered movie recommendations based on search query
filtered_movies = []
if search_query:
    for genre, titles in movies.items():
        for title in titles:
            if search_query.lower() in title.lower() or search_query.lower() in genre.lower():
                filtered_movies.append((genre, title))

# Display recommendations based on search
if st.button("Get Recommendations"):
    if filtered_movies:
        st.subheader("Recommendations:")
        for genre, title in filtered_movies:
            st.write(f"- **{title}** ({genre})")
    else:
        st.warning("No movies found matching your search.")
else:
    st.subheader("Browse by Genre:")
    for genre in movies.keys():
        st.write(f"- **{genre}**")
